### ISSUE TITLE
milvus-operator deployment does not support imagePullSecrets

### ISSUE THREAD

**Issue by douglarek** [zilliztech/milvus-operator#104]
### Description:
1. **Why this feature is needed:**
   - Sometimes, pulling images from Docker Hub can be slow in the company's environment. There is a need to replace it with the company's internally maintained image repository to accelerate the process.

2. **Current limitation:**
   - The milvus-operator deployment currently lacks support for imagePullSecrets, making it challenging to authenticate and pull images from private registries. When attempting to edit the deployment to include imagePullSecrets, an error occurs indicating that the field is unrecognized.

3. **Steps to reproduce:**
   - Edit the existing deployment in the milvus-operator namespace using the following command:
     ```
     kubectl edit deployment -n milvus-operator
     ```
   - Modify the deployment manifest to include the desired image and imagePullSecrets, as follows:
     ```yaml
     image: 'corp.domain/xxx/milvus-operator:v0.8.6'
     imagePullSecrets:
       - name: docker-registry
     ```
   - Observe the error message encountered:
     ```
     # * <nil>: Invalid value: "The edited file failed validation": ValidationError(Deployment.spec.template.spec.containers[0]): unknown field "imagePullSecrets" in io.k8s.api.core.v1.Container
     ```

**Comment by haorenfsa** [comment]
@douglarek Yes, but it's also true that the helm chart of milvus-operator also provides a `imagePullSecrets` field without implementation.

**Comment by bcbrockway** [comment]
> @douglarek Yes, but it's also true that the helm chart of milvus-operator also provides a `imagePullSecrets` field without implementation.

Came here to report this just now.
