### ISSUE TITLE
报错Endpoint url cannot have fully qualified paths

### ISSUE THREAD

**Issue by lhx692135353** [zilliztech/milvus-operator#109]
日志：[2024/04/23 03:28:06.965 +00:00] [ERROR] [querynodev2/server.go:312] ["QueryNode init vector storage failed"] [error="Endpoint url cannot have fully qualified paths."] [stack="github.com/milvus-io/milvus/internal/querynodev2.(*QueryNode).Init.func1\n\t/go/src/github.com/milvus-io/milvus/internal/querynodev2/server.go:312\nsync.(*Once).doSlow\n\t/usr/local/go/src/sync/once.go:74\nsync.(*Once).Do\n\t/usr/local/go/src/sync/once.go:65\ngithub.com/milvus-io/milvus/internal/querynodev2.(*QueryNode).Init\n\t/go/src/github.com/milvus-io/milvus/internal/querynodev2/server.go:279\ngithub.com/milvus-io/milvus/internal/distributed/querynode.(*Server).init\n\t/go/src/github.com/milvus-io/milvus/internal/distributed/querynode/service.go:135\ngithub.com/milvus-io/milvus/internal/distributed/querynode.(*Server).Run\n\t/go/src/github.com/milvus-io/milvus/internal/distributed/querynode/service.go:231\ngithub.com/milvus-io/milvus/cmd/components.(*QueryNode).Run\n\t/go/src/github.com/milvus-io/milvus/cmd/components/query_node.go:55\ngithub.com/milvus-io/milvus/cmd/roles.runComponent[...].func1\n\t/go/src/github.com/milvus-io/milvus/cmd/roles/roles.go:111"]
[2024/04/23 03:28:06.965 +00:00] [ERROR] [querynode/service.go:136] ["QueryNode init error: "] [error="Endpoint url cannot have fully qualified paths."] [stack="github.com/milvus-io/milvus/internal/distributed/querynode.(*Server).init\n\t/go/src/github.com/milvus-io/milvus/internal/distributed/querynode/service.go:136\ngithub.com/milvus-io/milvus/internal/distributed/querynode.(*Server).Run\n\t/go/src/github.com/milvus-io/milvus/internal/distributed/querynode/service.go:231\ngithub.com/milvus-io/milvus/cmd/components.(*QueryNode).Run\n\t/go/src/github.com/milvus-io/milvus/cmd/components/query_node.go:55\ngithub.com/milvus-io/milvus/cmd/roles.runComponent[...].func1\n\t/go/src/github.com/milvus-io/milvus/cmd/roles/roles.go:111"]
[2024/04/23 03:28:06.965 +00:00] [ERROR] [components/query_node.go:56] ["QueryNode starts error"] [error="Endpoint url cannot have fully qualified paths."] [stack="github.com/milvus-io/milvus/cmd/components.(*QueryNode).Run\n\t/go/src/github.com/milvus-io/milvus/cmd/components/query_node.go:56\ngithub.com/milvus-io/milvus/cmd/roles.runComponent[...].func1\n\t/go/src/github.com/milvus-io/milvus/cmd/roles/roles.go:111"]
panic: Endpoint url cannot have fully qualified paths.

配置文件：
kubectl get configmap chat-with-project -n milvus -o yaml                                                                                                                                                         ✔  10376  11:21:24
apiVersion: v1
data:
  user.yaml: |
    etcd:
      endpoints:
      - chat-with-project-etcd.milvus:2379
      rootPath: chat-with-project
    kafka:
      brokerList:
      - kafka-kafka-bootstrap.kafka.svc.cluster.local:9092
    messageQueue: kafka
    minio:
      accessKeyID: yv0izXj8r3vAESYi
      address: minio.milvus.svc.cluster.local
      bucketName: milvus
      port: 80
      secretAccessKey: 7pvFwMXsLbNzufv4ljVoHORy7OaZxVEQ
      useSSL: false
    mq:
      type: kafka
    msgChannel:
      chanNamePrefix:
        cluster: chat-with-project
kind: ConfigMap
metadata:
  creationTimestamp: "2024-04-23T03:13:09Z"
  labels:
    app.kubernetes.io/instance: chat-with-project
    app.kubernetes.io/managed-by: milvus-operator
    app.kubernetes.io/name: milvus
  name: chat-with-project
  namespace: milvus
  ownerReferences:
  - apiVersion: milvus.io/v1beta1
    blockOwnerDeletion: true
    controller: true
    kind: Milvus
    name: chat-with-project
    uid: 173d98b4-0572-4481-87b4-e277256bd536
  resourceVersion: "28183349"
  uid: 0e4eb5a3-1b6f-4b3f-a13d-db046d80bfe6

**Comment by lhx692135353** [comment]
yaml 配置文件 
apiVersion: milvus.io/v1beta1
kind: Milvus
metadata:
  namespace: milvus
  name: chat-with-project
  labels:
    app: milvus
spec:
  components:
    dataCoord:
      resources:
        limits:
          cpu: "0.5"
          memory: 2Gi
    queryCoord:
      resources:
        limits:
          cpu: "0.5"
          memory: 2Gi
    indexCoord:
      resources:
        limits:
          cpu: "0.5"
          memory: 2Gi
    rootCoord:
      resources:
        limits:
          cpu: 1
          memory: 2Gi
    dataNode:
      replicas:  1
      resources:
        limits:
          cpu: 1
          memory: 4Gi
    indexNode:
      replicas: 1
      resources:
        limits:
          cpu: 4
          memory: 8Gi
    queryNode:
      replicas: 1
      resources:
        limits:
          cpu: 3
          memory: 12Gi
    proxy:
      replicas: 1
      resources:
        limits:
          cpu: 1
          memory: 4Gi
  config: 
    minio:
      bucketName: "milvus"
      useSSL: false
  dependencies:
    etcd:
      inCluster:
        values:
          autoCompactionMode: revision
          autoCompactionRetention: "1000"
          extraEnvVars:
          - name: ETCD_QUOTA_BACKEND_BYTES
            value: "4294967296"
          - name: ETCD_HEARTBEAT_INTERVAL
            value: "500"
          - name: ETCD_ELECTION_TIMEOUT
            value: "25000"
          - name: ETCD_SNAPSHOT_COUNT
            value: "10000"
          - name: ETCD_ENABLE_PPROF
            value: "true"
          persistence:
            accessMode: ReadWriteOnce
            enabled: true
            size: 30Gi   #SSD Required
            storageClass: nfs-client
          replicaCount: 3
          resources:
            limits:
              cpu: 1
              memory: 2Gi
            requests:
              cpu: 1
              memory: 2Gi
    msgStreamType: kafka
    kafka:
      external: true
      brokerList: 
        - "kafka-kafka-bootstrap.kafka.svc.cluster.local:9092"
    storage:
      external: true
      type: MinIO
      endpoint: "minio.milvus.svc.cluster.local"
      secretRef: milvus-minio

**Comment by yhmo** [comment]
minio port = 80?

**Comment by lhx692135353** [comment]
没开https, 对应service 就是80，用的minio的operator创建的

**Comment by lhx692135353** [comment]
> minio port = 80?

没开https, 对应service 就是80，用的minio的operator创建的

**Comment by yhmo** [comment]
等milvus-operator的owner @LoveEachDay 来诊

**Comment by LoveEachDay** [comment]
这个问题主要是因为minio 和milvus 安装在同一个namespace 里面， kuberntes 默认会注入service 的environment variable 进来。你可以把milvus 部署到另外的namespace 就可以了。

**Comment by lhx692135353** [comment]
> 等milvus-operator的owner @LoveEachDay 来诊

我已经找到了解决方案，因为我把minio和milvus部署到了一个集群里，[解决问题的链接](https://github.com/milvus-io/milvus/issues/28032)
