### ISSUE TITLE
FAQ doc for webhook cert related issue

### ISSUE THREAD

**Issue by haorenfsa** [zilliztech/milvus-operator#132]
solution in https://github.com/milvus-io/milvus/issues/21961

related issue:
https://github.com/zilliztech/milvus-operator/issues/108
https://github.com/milvus-io/milvus/issues/33827

**Comment by nustiueudinastea** [comment]
@haorenfsa any idea why the cert.yaml is not part of the operator chart?

When looking at the operator instructions on this page: https://milvus.io/docs/install_cluster-milvusoperator.md, you can see in the example that the issuer and certificate resources are installed. But actually, the issuer and certificate resources are neither part of the chart, nor the standalone deployment.yaml. So probably the instructions doc was created with a different set of files.

<img width="922" alt="Screenshot 2024-10-23 at 16 53 39" src="https://github.com/user-attachments/assets/ce2c878a-e8de-4ac3-8a83-e975de9c9324">

**Comment by haorenfsa** [comment]
Hi @nustiueudinastea 

> any idea why the cert.yaml is not part of the operator chart?
it's because the cert is dependent on cert-manager. Maybe we should make cert-manager's chart a dependency of milvus-operator directly.


There's now a walkaround to use a deployment without webhook: [deployment-no-webhook.yaml](https://github.com/zilliztech/milvus-operator/releases/download/v1.0.9/deployment-no-webhook.yaml)

**Comment by nustiueudinastea** [comment]
I don't think the chart should have a direct dependency on cert-manager, because most people already have that on their clusters. To me it makes more sense to create the certificate and issuer in the milvus-operator chart, but make it optional, with the ability to enable or disable it via a values.yaml flag, for people that might need to manage that in a different way.

**Comment by haorenfsa** [comment]
@nustiueudinastea Yeah, I agreee. let's do this in next release.
