### ISSUE TITLE
main milvusdb/milvus-operator:v1.0.3 not found

### ISSUE THREAD

**Issue by Ghostwritten** [zilliztech/milvus-operator#166]
`
$ nerdctl rmi milvusdb/milvus-operator:v1.0.3
WARN[0000] failed to enumerate rootfs                    error="unexpected media type text/html for sha256:5af2dbaf6657d599f78d863a9cb56c5b48a6842326aec1dfcd548b58113906e3: not found"
`

**Comment by haorenfsa** [comment]
Hi @Ghostwritten, it's due to the bump version patch is merged without adding a release tag. It's released today, please try again
