### ISSUE TITLE
exec user process caused: exec format error

### ISSUE THREAD

**Issue by lysShub** [zilliztech/milvus-operator#18]
`kubectl apply -f https://raw.githubusercontent.com/zilliztech/milvus-operator/main/deploy/manifests/deployment.yaml`

```shell
vecdb@pve-223-x86:~/milvus-install$ kubectl get pods -n milvus-operator
NAME                               READY   STATUS              RESTARTS   AGE
milvus-operator-68c6964984-vhn9w   0/1     ContainerCreating   0          5m14s
milvus-operator-checker-q2v87      0/1     CrashLoopBackOff    5          5m14s
vecdb@pve-223-x86:~/milvus-install$ kubectl logs milvus-operator-checker-q2v87 -n milvus-operator
standard_init_linux.go:228: exec user process caused: exec format error
vecdb@pve-223-x86:~/milvus-install$
```

**Comment by lysShub** [comment]
`milvusdb/milvus-operator` not support arm64 ?

**Comment by lysShub** [comment]
> `milvusdb/milvus-operator` not support arm64 ?

https://milvus.io/docs/prerequisite-helm.md ?

**Comment by gruberdev** [comment]
> > `milvusdb/milvus-operator` not support arm64 ?
> 
> [milvus.io/docs/prerequisite-helm.md](https://milvus.io/docs/prerequisite-helm.md)

As far I am aware, the list of CPU instructions listed as requirements are all x86 exclusive:

- SSE4.2
- AVX
- AVX2
- AVX-512

This can be observed on the list of supported architectures [in the Docker hub image tag page](https://hub.docker.com/r/milvusdb/milvus-operator/tags).

**Comment by lysShub** [comment]
> > > `milvusdb/milvus-operator` not support arm64 ?
> > 
> > 
> > [milvus.io/docs/prerequisite-helm.md](https://milvus.io/docs/prerequisite-helm.md)
> 
> As far I am aware, the list of CPU instructions listed as requirements **are all x86 exclusive**:
> 
> > * SSE4.2
> > * AVX
> > * AVX2
> > * AVX-512
> 
> This can be further observed on the list of supported architectures [in the Docker hub image tag page](https://hub.docker.com/r/milvusdb/milvus-operator/tags).

add nodeSelector

**Comment by haorenfsa** [comment]
@lysShub Hi, Arm image is in beta, if you want to try out, search for "arm" in milvus' dockerhub repo to find beta images.
<img width="1401" alt="image" src="https://github.com/zilliztech/milvus-operator/assets/15938850/a71f730b-0378-4524-98c1-65bd6eed4dee">

**Comment by strongit** [comment]
we use milvus-operator:v1.3.4 still have this problem,k8s version v1.20.14. Pls help check that,tks

<img width="581" height="138" alt="Image" src="https://github.com/user-attachments/assets/c6762857-3b14-4dae-9ecf-281fcd80a157" />
