### ISSUE TITLE
can't change the default proxy port

### ISSUE THREAD

**Issue by Peter-YoungUk** [zilliztech/milvus-operator#194]
Hi, I'm operating Milvus services using Milvus Operator. 
When I tried to change the Milvus proxy port from 19530 to another port, it didn't seem to work properly. 
I think the component's port is fixed to the default port by the source code.
Is that the intended behavior?

https://github.com/zilliztech/milvus-operator/blob/6ba3ce93f46481867f0903e0e926ae8ce4263a35/pkg/controllers/components.go#L309-L312

https://github.com/zilliztech/milvus-operator/blob/6ba3ce93f46481867f0903e0e926ae8ce4263a35/pkg/controllers/components.go#L265-L307

**Comment by haorenfsa** [comment]
@Peter-YoungUk Yes. Milvus itself supports configuring custom ports. But for now milvus-operator only supports changing ports of restful service.
https://github.com/zilliztech/milvus-operator/blob/6ba3ce93f46481867f0903e0e926ae8ce4263a35/apis/milvus.io/v1beta1/components_types.go#L298.

**Comment by Peter-YoungUk** [comment]
@haorenfsa 
Thanks for your information of that configuration.
