### ISSUE TITLE
The milvus cluster is installed with helm. Can I use  milvus-operator to upgrade it?

### ISSUE THREAD

**Issue by ytcisme** [zilliztech/milvus-operator#195]
There is a milvus cluster in my k8s cluster，it is installed with milvus chart.  Can I use milvus-operator with MilvusUpgrade CRD  to upgrade the milvus cluster  which is not installed by milvus-operator？

**Comment by haorenfsa** [comment]
Hi, @ytcisme  I guess the MilvusUpgrade CRD is not what you want. It is only used for upgrade from v2.1.x to v2.2.x. https://github.com/zilliztech/milvus-operator/blob/main/docs/administration/upgrade.md.
It does the following things: backup the meta, stop the instance, upgrade the metadata version to v2.2, then restart the instance.

If you only want to upgrade image, you only need to change the image the image of milvus deployments.

And if you use milvus-operator, there will be likely less downtime. But we haven't support migration from helm chart to operator, yet.

**Comment by ytcisme** [comment]
> Hi, @ytcisme I guess the MilvusUpgrade CRD is not what you want. It is only used for upgrade from v2.1.x to v2.2.x. https://github.com/zilliztech/milvus-operator/blob/main/docs/administration/upgrade.md. It does the following things: backup the meta, stop the instance, upgrade the metadata version to v2.2, then restart the instance.
> 
> If you only want to upgrade image, you only need to change the image the image of milvus deployments.
> 
> And if you use milvus-operator, there will be likely less downtime. But we haven't support migration from helm chart to operator, yet.

Thank you，I get it.
