### ISSUE TITLE
Suggestion for Configuring Dummy Image via CRD

### ISSUE THREAD

**Issue by Peter-YoungUk** [zilliztech/milvus-operator#208]
Hi everyone,

I appreciate the recent change of using a dummy image for querynode to stabilize rolling updates. However, I’ve encountered an issue: our system does not allow the use of external images, so this update (v1.1.1) didn’t work for us.
https://github.com/zilliztech/milvus-operator/pull/203/files

To address this, my current solution is to patch the code every time a new version is released, which is not ideal.

Would it be possible to add the dummy image name as a configurable option through the CRD? This would make it easier for us to use the milvus-operator without the extra burden.

Thank you!

**Comment by haorenfsa** [comment]
Yes, it's reasonable

**Comment by haorenfsa** [comment]
@Peter-YoungUk By the way, would you like to make the patch by yourself?

**Comment by Peter-YoungUk** [comment]
@haorenfsa 
Thank you very much for the kind suggestion, but due to personal and work schedules overlapping, it seems like it will take a lot of time to fully understand the code and apply the patch. I will definitely try to contribute in the future.
I will use version 1.1.0 until the patch is applied.

**Comment by haorenfsa** [comment]
No worries, we'll make a patch soon.
