### ISSUE TITLE
Deleting the Milvus object does not delete etcd and minio 

### ISSUE THREAD

**Issue by nairan-deshaw** [zilliztech/milvus-operator#216]
I am using the standalone mode using Milvus operator in the non embedded mode. This is creating three containers - etcd, minio and milvus. However when we delete the created Milvus object, it does not delete the other two components and we have to manually delete it. Is this expected? Can it be fixed if not.

Thanks.

**Comment by haorenfsa** [comment]
Hi @nairan-deshaw , it's working as expected. You may refer to https://github.com/zilliztech/milvus-operator/blob/main/config/samples/milvus_deletion.yaml, to config operator to delete dependencies when delete `Milvus` Object.

**Comment by nairan-deshaw** [comment]
Thanks @haorenfsa, that was helpful - it works now.
