### ISSUE TITLE
is grafana available on the operator?

### ISSUE THREAD

**Issue by webcoderz** [zilliztech/milvus-operator#40]
can we enable grafana with the operator or cluster?

**Comment by haorenfsa** [comment]
We haven't release a formal grafana dashboard for milvus-operator yet, but you can find the dashboard for milvus cluster in milvus repo:
https://github.com/milvus-io/milvus/tree/master/deployments/monitor/grafana

**Comment by haorenfsa** [comment]
The metric export is by default enabled, for milvus in port 9091, and for milvus-operator in port 8080.

**Comment by webcoderz** [comment]
okay thanks i see them active, but doesnt seem like the kube prom stack with prometheus operator is able to find the metrics

**Comment by haorenfsa** [comment]
you mean metrics of milvus or operator, or both of them?

**Comment by webcoderz** [comment]
Yea both, I was able to port forward and see the metrics functional but the prometheus operator didn't find them when I added the dashboard

**Comment by haorenfsa** [comment]
under your milvus' namespace, could you find the `PodMonitor` created by milvus-operator? and which version of prometheus operator are you using?

**Comment by webcoderz** [comment]
Just saw this Will check tomorrow when I am back in front of my cluster

**Comment by webcoderz** [comment]
Okay seems like ArgoCD is having trouble with the operator and it's stuck in progressing , I have to delete and redeploy or something

**Comment by webcoderz** [comment]
Got it working.. the argoCD was having issues so once I reset metrics came up. Thanks! 🙏

**Comment by webcoderz** [comment]
okay so i just changed form milvus standalone to milvus cluster, and same issue, i port forward and can see the metrics on both the operator and the cluster, and i load in the json dashboard and it cant pick up the metrics from the services
