### ISSUE TITLE
question: is this operator prefer over milvus-helm chart?

### ISSUE THREAD

**Issue by tulequ** [zilliztech/milvus-operator#50]
I see both install method list on milvus site
But there is no note about which method should be prefer
So does this method will replace helm chart?

**Comment by haorenfsa** [comment]
No. If you're going to maintaining only 1 milvus in your cluster, or you're not worrying about the down time in upgrade, helm chart is your choice. Otherwise operator is perfered.

**Comment by tulequ** [comment]
thank you
