### ISSUE TITLE
The milvus.milvus.io stunk in `Deleting` status

### ISSUE THREAD

**Issue by yuzs2** [zilliztech/milvus-operator#52]
Hi, I was trying to delete a milvus using `kubectl delete -f milvus-sample.yml`, however the deleting was stunk, even the `--force --grace-period=0` won't help.

When describing milvus, it was stunk in `Deleting` status. 
```
NAME                             MODE         STATUS     UPDATED   AGE
milvus.milvus.io/milvus-sample   standalone   Deleting   True      91m
```
It could be stunk for hours. During the stunk, no Error was seen in the milvus-operator pods logs. The pod utilization was also not high.

Btw, I re-deployed the milvus-operator before I deleted the milvus. Would this be an issue?

**Comment by haorenfsa** [comment]
@yuzs2 Thank you for the feedback. It's a bug of assuming foreground deletion. it's fixed in #51. The patch will be included in next release (v0.8.6).

For now you can delete it by `kubectl delete --cascade=foreground`.
