### ISSUE TITLE
What is the difference between milvus operator and milvus helm?

### ISSUE THREAD

**Issue by Uijeong97** [zilliztech/milvus-operator#57]
I'm curious about the role of the operator. 
Is it different from a [Helm deployment](https://github.com/milvus-io/milvus-helm)?

It states that the milvus operator supports high availability.
I was wondering if it also offers features not supported by milvus helm.
For example, query node graceful shutdown.

**Comment by haorenfsa** [comment]
Yes, milvus-operator aims to support rolling update without downtime. For now, there is still about 60s down time when rolling coordinators, and we will keep polishing this feature.

There're some other features to be scheduled, like data migration between Milvus clusters, database snapshots & recover, which are already available in [Zilliz Cloud](https://cloud.zilliz.com/). We may bring them up to operator someday.

**Comment by haorenfsa** [comment]
Updated in readme https://github.com/zilliztech/milvus-operator?tab=readme-ov-file#milvus-operator-vs-helm
