### ISSUE TITLE
cluster keeps restarting 

### ISSUE THREAD

**Issue by webcoderz** [zilliztech/milvus-operator#63]
this thing cannot stay up for longer than 2 days n a production cluster before it starts not responding, i cant trust it under load, i cant even delete it from the cluster it wont let me

**Comment by webcoderz** [comment]
is there an actual stable version? its been like this for months

**Comment by haorenfsa** [comment]
@webcoderz Thank you for the feedback. Cloud you also provide logs so that we can better understand what's going on? Thank you again in advance! 

By the way as I know it's being used by a couple of organizations in production environment for years, it's quite stable.

**Comment by webcoderz** [comment]
sorry, for being frustrated, just breaks alot, what logs would you specifically need? here is my milvus cluster yaml


`apiVersion: milvus.io/v1beta1
kind: Milvus
metadata:
  name: cluster
  namespace: milvus
  labels:
    app: cluster
spec:
  mode: cluster
  components:
    dataNode:
      replicas: 2
    indexNode:
      replicas: 2
    queryNode:
      replicas: 2
    mixCoord:
      replicas: 1
  dependencies:
    etcd:
      inCluster:
        values:
          replicaCount: 1
        deletionPolicy: Delete
        pvcDeletion: true
    pulsar:
      inCluster:
        values:
          components: 
            autorecovery: false
            functions: false
            toolset: false
            pulsar_manager: false
          monitoring:
            prometheus: true
            grafana: false
            node_exporter: true
            alert_manager: false
          proxy:
            replicaCount: 1
            resources:
              requests:
                cpu: 0.01
                memory: 256Mi
            configData:
              PULSAR_MEM: >
                -Xms256m -Xmx256m
              PULSAR_GC: >
                -XX:MaxDirectMemorySize=256m
          bookkeeper:
            replicaCount: 2
            resources:
              requests:
                cpu: 0.01
                memory: 256Mi
            configData:
              PULSAR_MEM: >
                -Xms256m
                -Xmx256m
                -XX:MaxDirectMemorySize=256m
              PULSAR_GC: >
                -Dio.netty.leakDetectionLevel=disabled
                -Dio.netty.recycler.linkCapacity=1024
                -XX:+UseG1GC -XX:MaxGCPauseMillis=10
                -XX:+ParallelRefProcEnabled
                -XX:+UnlockExperimentalVMOptions
                -XX:+DoEscapeAnalysis
                -XX:ParallelGCThreads=32
                -XX:ConcGCThreads=32
                -XX:G1NewSizePercent=50
                -XX:+DisableExplicitGC
                -XX:-ResizePLAB
                -XX:+ExitOnOutOfMemoryError
                -XX:+PerfDisableSharedMem
                -XX:+PrintGCDetails
          zookeeper:
            replicaCount: 1
            resources:
              requests:
                cpu: 0.01
                memory: 256Mi
            configData:
              PULSAR_MEM: >
                -Xms256m
                -Xmx256m
              PULSAR_GC: >
                -Dcom.sun.management.jmxremote
                -Djute.maxbuffer=10485760
                -XX:+ParallelRefProcEnabled
                -XX:+UnlockExperimentalVMOptions
                -XX:+DoEscapeAnalysis -XX:+DisableExplicitGC
                -XX:+PerfDisableSharedMem
                -Dzookeeper.forceSync=no
          broker:
            replicaCount: 1
            resources:
              requests:
                cpu: 0.01
                memory: 256Mi
            configData:
              PULSAR_MEM: >
                -Xms256m
                -Xmx256m
              PULSAR_GC: >
                -XX:MaxDirectMemorySize=256m
                -Dio.netty.leakDetectionLevel=disabled
                -Dio.netty.recycler.linkCapacity=1024
                -XX:+ParallelRefProcEnabled
                -XX:+UnlockExperimentalVMOptions
                -XX:+DoEscapeAnalysis
                -XX:ParallelGCThreads=32
                -XX:ConcGCThreads=32
                -XX:G1NewSizePercent=50
                -XX:+DisableExplicitGC
                -XX:-ResizePLAB
                -XX:+ExitOnOutOfMemoryError

  config:
    milvus:
      log:
        level: info

    component:
      proxy:
        timeTickInterval: 150




`

**Comment by haorenfsa** [comment]
I thought you mean `milvus-operator` constantly dies? or do you mean the `milvus cluster`? 

Before you reply, I assume it's the  `milvus cluster`.

From the configuration you provided, it's not suitable for production environment. It's like a minimum deployment. It use only 1 replica of etcd & only 256MB memory for pulsar pods. which may cause pulsar to crash easily when you insert data.

For production, try using the default dependencies configurations by leaving `dependencies: {}`:
```
apiVersion: milvus.io/v1beta1
kind: Milvus
metadata:
  name: my-release
  labels:
    app: milvus
spec:
  mode: cluster
  components:
    dataNode:
      replicas: 2
    indexNode:
      replicas: 2
    queryNode:
      replicas: 2
    mixCoord:
      replicas: 1
  config:
    milvus:
      log:
        level: info
    component:
      proxy:
        timeTickInterval: 150
  dependencies: {}
```
`milvus-operator` will fill the suitable configurations for you.

**Comment by webcoderz** [comment]
Okay thank you , yes it's the brokers that keep dying, I am only running single node for now but will be adding nodes soon once my bare metal nodes arrive, thank you I will see if this helps, and the operator itself is fine , this helps a lot .. thanks for your help! Will test it and let you know if I have problems from there

**Comment by haorenfsa** [comment]
both the in-cluster dependencies & PVCs are set to retain by default, to avoid data loss when you delete a production env milvus by mistake.

If you want milvus-operator to delete them after you deleted milvus, check the [demo manifest](https://github.com/zilliztech/milvus-operator/blob/main/config/samples/cluster_demo.yaml)

in short you need to add below config block for each dependency you use.
```yaml
inCluster:
  values:
    deletionPolicy: Delete
    pvcDeletion: true
```

**Comment by webcoderz** [comment]
Okay great thanks 🙏 and sorry for my frustrations
